### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by BuhtigithuB** [niphlod/welcome_augmented#3]
Hello,

Fall on this when trying welcome_augmented : 

Exception SyntaxError: invalid syntax (environment.py, line 51)
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/**main**.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 677, in run_with_paths
    self.load_hooks()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 631, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 303, in exec_file
    code = compile(f.read(), filename2, 'exec')
  File "features/environment.py", line 51
    print 'Sleeping before web2py starts...'

Tries to comment all the print statement and the problem get away...

**Comment by niphlod** [comment]
will look into it as soon as I get back from holidays

**Comment by cassiobotaro** [comment]
Is related to this @niphlod https://github.com/behave/behave/issues/288

**Comment by ejmvar** [comment]
Print works as python3 :
Use print (.......)
