### ISSUE TITLE
OperationalError: unable to open database file

### ISSUE THREAD

**Issue by BuhtigithuB** [niphlod/welcome_augmented#4]
Hello,

Another issue trying welcome_augmented...

Here the traceback : 

Traceback (most recent call last):
  File "/version_2112/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/version_2112/web2py/applications/welcome_augmented/models/db.py", line 14, in <module>
    db = DAL('sqlite://storage.sqlite',pool_size=1,check_reserved=['all'])
  File "/version_2112/web2py/gluon/packages/dal/pydal/base.py", line 174, in **call**
    obj = super(MetaDAL, cls).**call**(_args, *_kwargs)
  File "/version_2112/web2py/gluon/packages/dal/pydal/base.py", line 459, in **init**
    raise RuntimeError("Failure to connect, tried %d times:\n%s" % (attempts, tb))
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "/version_2112/web2py/gluon/packages/dal/pydal/base.py", line 437, in **init**
    self._adapter = ADAPTERS[self._dbname](**kwargs)
  File "/version_2112/web2py/gluon/packages/dal/pydal/adapters/base.py", line 57, in __call__
    obj = super(AdapterMeta, cls).**call**(_args, *_kwargs)
  File "/version_2112/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 78, in **init**
    if do_connect: self.reconnect()
  File "/version_2112/web2py/gluon/packages/dal/pydal/connection.py", line 105, in reconnect
    self.connection = f()
  File "/version_2112/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 76, in connector
    return self.driver.Connection(dbpath, **driver_args)
OperationalError: unable to open database file

**Comment by BuhtigithuB** [comment]
Forget about this one... Folder missing: 

app/databases
      /errors  
      /sessions
      /uploads
